apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- toYaml .Values.global.labels | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- toYaml .Values.deployment.selector.matchLabels | nindent 6 }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  progressDeadlineSeconds: {{ .Values.deployment.progressDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.deployment.template.metadata.labels | nindent 8 }}
      annotations:
        {{- toYaml .Values.deployment.template.metadata.annotations | nindent 8 }}
    spec:
      {{- if .Values.deployment.template.spec.containers }}
      containers:
        {{- toYaml .Values.deployment.template.spec.containers | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.template.spec.volumes }}
      volumes:
        {{- toYaml .Values.deployment.template.spec.volumes | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.deployment.template.spec.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.deployment.template.spec.securityContext | nindent 8 }}
      imagePullSecrets:
        {{- range .Values.deployment.template.spec.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      affinity:
        {{- toYaml .Values.deployment.template.spec.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.deployment.template.spec.tolerations | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.deployment.template.spec.nodeSelector | nindent 8 }}
      hostAliases:
        {{- toYaml .Values.deployment.template.spec.hostAliases | nindent 8 }}
      dnsPolicy: {{ .Values.deployment.template.spec.dnsPolicy }}
      hostNetwork: {{ .Values.deployment.template.spec.hostNetwork }}
      restartPolicy: {{ .Values.deployment.template.spec.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.deployment.template.spec.terminationGracePeriodSeconds }}
      schedulerName: {{ .Values.deployment.template.spec.schedulerName }}
      priorityClassName: {{ .Values.deployment.template.spec.priorityClassName }}
      runtimeClassName: {{ .Values.deployment.template.spec.runtimeClassName }}
