apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.specific.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  {{- if .Values.virtualService.gateways }}
  gateways:
    {{- toYaml .Values.virtualService.gateways | nindent 4 }}
  {{- end }}
  {{- if .Values.virtualService.hosts }}
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 4 }}
  {{- end }}
  {{- if .Values.virtualService.http }}
  http:
    {{- range .Values.virtualService.http }}
    - name: {{ .name }}
      match:
        {{- toYaml .match | nindent 6 }}
      rewrite:
        {{- toYaml .rewrite | nindent 6 }}
      route:
        {{- toYaml .route | nindent 6 }}
      corsPolicy:
        {{- toYaml .corsPolicy | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.virtualService.tls }}
  tls:
    {{- toYaml .Values.virtualService.tls | nindent 4 }}
  {{- end }}
  {{- if .Values.virtualService.tcp }}
  tcp:
    {{- toYaml .Values.virtualService.tcp | nindent 4 }}
  {{- end }}
  {{- if .Values.virtualService.exportTo }}
  exportTo:
    {{- toYaml .Values.virtualService.exportTo | nindent 4 }}
  {{- end }}

  # Configurações específicas do seu exemplo
  {{- if .Values.virtualService.specific }}
  gateways:
    {{- toYaml .Values.virtualService.specific.gateways | nindent 4 }}
  hosts:
    {{- toYaml .Values.virtualService.specific.hosts | nindent 4 }}
  http:
    {{- range .Values.virtualService.specific.http }}
    - name: {{ .name }}
      match:
        {{- toYaml .match | nindent 6 }}
      rewrite:
        {{- toYaml .rewrite | nindent 6 }}
      route:
        {{- toYaml .route | nindent 6 }}
      corsPolicy:
        {{- toYaml .corsPolicy | nindent 6 }}
    {{- end }}
  {{- end }}
