global:
  # Nome comum do aplicativo usado em recursos como parte do fullname
  appName: mfe-analyzes
  namespace: default
  labels: {} # Labels globais
  annotations: {} # Annotations globais

deployment:
  name: my-deployment
  replicas: 1
  selector:
    matchLabels: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    spec:
      containers: []
      volumes: []
      serviceAccountName: ""
      securityContext: {}
      imagePullSecrets: []

service:
  name: my-service
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-app
  loadBalancerIP: ""
  externalTrafficPolicy: ""
  sessionAffinity: ""
  clusterIP: ""
  externalName: ""
  externalIPs: []
  healthCheckNodePort: ""
  publishNotReadyAddresses: false
  sessionAffinityConfig: {}
  ipFamilies: []
  ipFamilyPolicy: ""
  allocateLoadBalancerNodePorts: true

virtualService:
  name: custom-virtual-service
  gateways: []
  hosts: []
  http:
    - match: []
      rewrite: {}
      route: []
      corsPolicy: {}
  tls: []
  tcp: []
  exportTo: ["*"]
  specific:
    name: "filtros-vs-ms"
    gateways: ["API-gateway"]
    hosts: ["api-qstudio-dev.meudominio.com"]
    http:
      - name: "filtros-ms"
        match:
          - uri:
              prefix: "/filtros-ms/"
        rewrite:
          uri: "/"
        route:
          - destination:
              host: "filtros-ms"
              port:
                number: 8080
        corsPolicy:
          allowCredentials: true
          allowHeaders: ["*"]
          allowMethods: ["POST", "OPTIONS", "GET", "PUT", "DELETE"]
          allowOrigins:
            - exact: "https://qstudio-dev.meudominio.com"
            - exact: "http://localhost:9000"
          exposeHeaders: ["Content-Length", "Content-Range"]
          maxAge: "10m"
